- hosts: all
  tasks:
  - name: Print creating file2
    debug: msg="Creating file2 in /home"
  - name: Creating a file2 with content
    copy:
      dest: "/home/ansible_script_file2.txt"
      content: |
        line 01 kuku!
        line 02 jojo2
