- hosts: all
  tasks:
  - name: Print message
    debug: msg="Plybook2! Creating another file at /home"
  - name: Creating a file2 with content
    copy:
      dest: "/home/Plybook2.txt"
      content: |
        kuku!
