- hosts: all
  tasks:
  - name: Print creating file
    debug: msg="Creating the file '{{P1}}.txt' in /home"
  - name: Creating a file with content
    copy:
      dest: "/home/{{P1}}.txt"
      content: |
        param value: {{P1}}
