- hosts: all
  tasks:
  - name: Print creating file
    debug: msg="Creating file ansible_script_file{{P1}} in /home"
  - name: Creating a file with content
    copy:
      dest: "/home/ansible_script_file{{P1}}.txt"
      content: |
        param value: {{P1}}
